### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by imrehg** [taipeihackerspace/mredison#1]
Occasionally have this issue:

```
02.08.15 22:12:42 [+0800] No handlers could be found for logger "irc.buffer"
02.08.15 22:12:42 [+0800] Traceback (most recent call last):
02.08.15 22:12:42 [+0800] File "/mredison/mredison.py", line 159, in <module>
02.08.15 22:12:42 [+0800] main()
02.08.15 22:12:42 [+0800] File "/mredison/mredison.py", line 156, in main
02.08.15 22:12:42 [+0800] bot.start()
02.08.15 22:12:42 [+0800] File "/usr/local/lib/python2.7/dist-packages/irc/bot.py", line 265, in start
02.08.15 22:12:42 [+0800] super(SingleServerIRCBot, self).start()
02.08.15 22:12:42 [+0800] File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 1247, in start
02.08.15 22:12:42 [+0800] self.reactor.process_forever()
02.08.15 22:12:42 [+0800] File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 278, in process_forever
02.08.15 22:12:42 [+0800] self.process_once(timeout)
02.08.15 22:12:42 [+0800] File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 259, in process_once
02.08.15 22:12:42 [+0800] self.process_data(i)
02.08.15 22:12:42 [+0800] File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 216, in process_data
02.08.15 22:12:42 [+0800] c.process_data()
02.08.15 22:12:42 [+0800] File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 583, in process_data
02.08.15 22:12:42 [+0800] for line in self.buffer:
02.08.15 22:12:42 [+0800] File "/usr/local/lib/python2.7/dist-packages/irc/buffer.py", line 102, in lines
02.08.15 22:12:42 [+0800] self.handle_exception()
02.08.15 22:12:42 [+0800] File "/usr/local/lib/python2.7/dist-packages/irc/buffer.py", line 100, in lines
02.08.15 22:12:42 [+0800] yield line.decode(self.encoding, self.errors)
02.08.15 22:12:42 [+0800] File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
02.08.15 22:12:42 [+0800] return codecs.utf_8_decode(input, errors, True)
02.08.15 22:12:42 [+0800] UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 68: invalid continuation byte
```

Find root cause (it's settings in the IRC library, I'm pretty sure), replicate, and mitigate.

**Comment by imrehg** [comment]
[Test char](http://stackoverflow.com/questions/6180521/unicodedecodeerror-utf8-codec-cant-decode-bytes-in-position-3-6-invalid-dat) to use:

```
ö
```
